### ISSUE TITLE
Cannot read property x of undefined

### ISSUE THREAD

**Issue by rvanbaalen** [Leaflet/Leaflet#2606]
When using Leaflet in combination with Angular Leaflet Directive, this error triggers when switching back and forth between a view with Leaflet and a view without leaflet.

Digging into the source, I discovered that `.setPosition` is being called regardless of the fact that `_getPos()` returns undefined.

**Comment by TheCodeDestroyer** [comment]
Actually this issue was not solved completely, I would suggest that since `.setPosition` is being called from numerous places that, it should handle an `undefined` value in itself and maybe return a `console.warn` if needed.

**Comment by mourner** [comment]
@TheCodeDestroyer did you run into this in a different use case?

**Comment by TheCodeDestroyer** [comment]
@mourner Yeah, for me it's called from `_resetView` and `_setPos` and it's `undefined`.

**Comment by MichalMisiaszek** [comment]
I am pretty sure I pass defined values still:
```TypeError: Cannot read property 'x' of undefined
    at Object.o.DomUtil.getTranslateString (http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js:6:12022)
    at Object.o.DomUtil.setPosition (http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js:6:12269)
    at o.PosAnimation.o.Class.extend.stop (http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js:9:21668)
    at o.Map.include.setView (http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js:9:22680)
    at o.Map.o.Class.extend.panTo (http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js:6:20298)
    at dashboard_panMapTo (chrome-extension://cglcekmhahoaabjeckolnegapcjlcfpj/main.js:702:17)```
