### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by irshad-platalytics** [Leaflet/Leaflet#3220]
I am facing issue "ReferenceError: window is not defined" using leaflet with nodeJs in as:

c:\Projects\Leaflet\node_modules\leaflet\dist\leaflet-src.js:9180
}(window, document));
  ^
ReferenceError: window is not defined
    at Object.<anonymous> (c:\Projects\Leaflet\node_modules\leaflet\dist\leaflet-src.js:9180:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Projects\Leaflet\app.js:7:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by jfirebaugh** [comment]
Based on your backtrace it looks like you're trying to use it in node or some other non-browser environment, which isn't going to work. Leaflet is a browser library.
