### ISSUE TITLE
eslint breaks unit tests

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet#4613]
In my linux environment, the command-line unit tests are failing with the following stack trace:

```
ivan:~/devel/Leaflet\ $ jake test
Checking for JS errors...
Cannot find module 'eslint-config-package.json'
Error: Cannot find module 'eslint-config-package.json'
    at Object.ModuleResolver.resolve (/home/ivan/devel/Leaflet/node_modules/eslint/lib/util/module-resolver.js:75:19)
    at resolve (/home/ivan/devel/Leaflet/node_modules/eslint/lib/config/config-file.js:473:33)
    at Object.load (/home/ivan/devel/Leaflet/node_modules/eslint/lib/config/config-file.js:490:24)
    at loadConfig (/home/ivan/devel/Leaflet/node_modules/eslint/lib/config.js:64:33)
    at new Config (/home/ivan/devel/Leaflet/node_modules/eslint/lib/config.js:197:38)
    at CLIEngine.executeOnFiles (/home/ivan/devel/Leaflet/node_modules/eslint/lib/cli-engine.js:585:28)
    at Object.cli.execute (/home/ivan/devel/Leaflet/node_modules/eslint/lib/cli.js:181:95)
    at Object.<anonymous> (/home/ivan/devel/Leaflet/node_modules/eslint/bin/eslint.js:77:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
jake aborted.
```

I suspect this is due to the changes made in #4571. I need to check why this doesn't fail in Jenkins, and read some eslint documentation.

**Comment by mourner** [comment]
Does the above fix it for you?

**Comment by IvanSanchez** [comment]
@mourner Yeah, the tests run again after pulling the latest `master` branch.
