### ISSUE TITLE
Circle.getBounds() throw error in 1.0.0 version

### ISSUE THREAD

**Issue by atomiomi** [Leaflet/Leaflet#4978]
This bug was already fixed in previous version https://github.com/Leaflet/Leaflet/issues/1068. But it occurs in new leaflet version.

Here is fiddle - https://jsfiddle.net/kecmw7ms/5/
Tested in Chrome Version 53, Firefox Version 47, Safari Version 10.0

Notes:
- Adding `circle` to the map makes it work
- Removing `setView` from map breaks it again

**Comment by IvanSanchez** [comment]
This is expected. The bounds will be different depending on the CRS, and a circle itself doesn't have a CRS - it depends on the map to access the CRS and do the proper calculations.

It's possible to throw a more verbose error or add to the documentation, but that's about it.

**Comment by atomiomi** [comment]
@IvanSanchez so it also expected that `getBounds` throws error when view was not set on map and that `getBounds` returns different LatLngBounds depending on current map view?

**Comment by IvanSanchez** [comment]
> so it also expected that `getBounds` throws error when view was not set on map

OK, that *might* be a bug. The calls to `this._map.layerPointToLatLng()` might be able to be changed into `this._map.options.crs.project()`.

**Comment by rgbkrk** [comment]
Possibly related - within our test suite we're running into the bounds being invalid. I've gone ahead and created a repository for reproducing the issue:

https://github.com/rgbkrk/leaflet-issue-reproduction

```bash
git clone https://github.com/rgbkrk/leaflet-issue-reproduction
cd leaflet-issue-reproduction
npm i
node reproduce.js
```

Expect to see:

```js
/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:1609
    throw new Error('Invalid LatLng object: (' + lat + ', ' + lng + ')');
    ^

Error: Invalid LatLng object: (NaN, NaN)
    at Object.L.LatLng (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:1609:9)
    at Object.L.Projection.SphericalMercator.unproject (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:2019:10)
    at Object.L.CRS.pointToLatLng (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:2062:26)
    at L.Map.L.Evented.extend.unproject (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:2877:27)
    at L.GridLayer.L.Layer.extend._updateLevels (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:4135:35)
    at L.GridLayer.L.Layer.extend._setView (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:4287:9)
    at L.GridLayer.L.Layer.extend._resetView (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:4263:8)
    at L.GridLayer.L.Layer.extend.onAdd (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:3911:8)
    at L.Layer.L.Evented.extend._layerAdd (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:3542:8)
    at L.Evented.L.Class.extend.fire (/Users/kylek/code/src/github.com/rgbkrk/leaflet-issue-reproduction/node_modules/leaflet/dist/leaflet-src.js:588:11)
```

The bounds looks like the right object, but I'm assuming that when we try to fitBounds it isn't able to do it?

**Comment by Rafnuss** [comment]
Sorry, I'm new to that but I'm not sure why it has been close. I still have the same issue (and the fiddle too - https://jsfiddle.net/kecmw7ms/7/)

I manage to make it work with an very non-elegant way...

`
		circle.addTo(map)
		map.fitBounds(circle.getBounds());
		circle.removeFrom(map)
`

**Comment by KrishnaPG** [comment]
This bug still exists in the 1.2.0 version. The `getBounds()` method is using the map object to compute the bounds, assuming that the circle already is attached to a map. Other objects, such as polygon etc. seem to be using `unproject` to compute the bounds

The `getBounds()` method could be called before the object is added to a map (especially when user drawn). Assuming that getBounds() has a valid map, is bug.

**Comment by perliedman** [comment]
@KrishnaPG well yes, that is why the issue is still open. If you look at @IvanSanchez's [comment](https://github.com/Leaflet/Leaflet/issues/4978#issuecomment-250677908) there is a suggestion on a possible workaround, but no one has gotten around to do something about it.

**Comment by jospin2017** [comment]
salut ! . ce bug a déjà été corrige ?

**Comment by ghybs** [comment]
Hi,

For reference, it seems to me that there is a reason why the [GeoJSON standard](https://tools.ietf.org/html/rfc7946) does _not_ specify a Circle geometry: it is much more difficult to accurately manipulate.

A polygon and other "angled" shapes are defined by point positions / nodes with explicit coordinates, and it is trivial to determine their bounds by iterating through those nodes, independently from any CRS.

On the contrary, a Circle that is specified by a center position and a radius (or diameter), i.e. a _distance_, will have different bounds depending on the CRS, because only the latter can provide a relation between distances and coordinates.

E.g. imagine a Circle covering the bright side of the Moon: center [0, 0], radius = 1/4 of moon perimeter. => bounds [[90, 90], [-90, -90]] (not exactly sure how to represent them, but you get the idea)
Now take that Circle _with same radius_ and apply it on Earth: it will definitely not touch the poles, hence North and South latitudes of its bounds will be much less than 90 degrees in absolute.

Therefore it is _impossible_ to compute a Circle bounds without knowing the CRS.

**Comment by ibesora** [comment]
Having found this bug recently and seeing there has been discussion about this since 2012 (https://github.com/Leaflet/Leaflet/issues/1068) without solving the issue, I'd like to propose the following:
- Use the current implementation (which uses the map CRS) of `Circle.getBounds()` when the circle has been added to a map
- Use the approximation found [here](https://github.com/Leaflet/Leaflet/commit/cca3180f30488aac08b50eda5f7620326050386b) by @mourner when the circle hasn't yet been added to the map
- Update the documentation to reflect this behaviour

Even if it's not the optimal solution I think we can all agree that `Circle.getBounds()` crashing when it hasn't been added to a map is less than ideal. `Polyline`, `Polygon` and `FeatureGroups` (that don't contain `Circles`) do not need to have been added to the map before calling `getBounds()`. 

Related issues: https://github.com/Leaflet/Leaflet/issues/1037, https://github.com/Leaflet/Leaflet/issues/1068, https://github.com/Leaflet/Leaflet/issues/1463, https://github.com/Leaflet/Leaflet/issues/1465, https://github.com/Leaflet/Leaflet/pull/1473
