### ISSUE TITLE
Running tests depending on leaflet headlessly

### ISSUE THREAD

**Issue by colbin8r** [Leaflet/Leaflet#5613]
I'm writing a plugin that uses Leaflet. For my plugin, I have a reasonably large suite of unit tests powered by [Mocha](https://mochajs.org), [Chai](http://chaijs.com/), [Sinon](http://sinonjs.org/), etc. My plugin is structured as a series of ES6 modules (hats off to the folks who shipped Leaflet 1.1.0!).

In my unit tests, I've tried to `import { Map } from 'leaflet', but this causes the tests to break because leaflet depends upon a global `window` resulting in a `ReferenceError: window is not defined` error in a headless environment like Node. I've been able to use pieces of Leaflet in my tests thanks to the [leaflet-headless](https://github.com/jieter/leaflet-headless) package, which sort of hacks over the global `window` dependency and allows me to `import { Map } from 'leaflet-headless'` and the like.

Note: I don't actually test Maps themselves (I understand I'd need to use [Phantom](phantomjs.org) or something to do that), but I need access to Maps, Layers, etc. to both extend and test my extensions programmatically.

Especially since 1.1.0 Leaflet has shifted towards ES6 modules, it would be really nice to have Leaflet recognize that it's in a headless environment and not depend upon a global `window`, even if that means not [setting the global L](https://github.com/Leaflet/Leaflet/issues/2364) and the like (which [doesn't seem like a good idea](https://yuiblog.com/blog/2006/06/01/global-domination/) anyway).

If this is something that you would consider contributions towards, let me know. I can look closer at the source and see if it's something I'd have the knowledge/time to be able to do.

## How to reproduce

- Leaflet version I'm using: 1.1.0 / 1.0.3
- OS/Platform (with version) I'm using: `node v6.11.0`
- `import { Map } from 'leaflet'` or import any other module from Leaflet
- transpile code with Babel
- resulting errors:
```
ReferenceError: window is not defined
    at Object.<anonymous> (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/leaflet/dist/leaflet-src
.js:13250:3)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/dev/Leaflet.Control.NestedLayers/
node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at L$1__default (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/esri-leaflet/dist/esri-leaflet
-debug.js:5:82)
    at Object.<anonymous> (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/esri-leaflet/dist/esri-l
eaflet-debug.js:8:2)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/dev/Leaflet.Control.NestedLayers/
node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/dev/Leaflet.Control.NestedLayers/src/Leaflet.LayerHierarchy.MapServerP
arser.js:10:1)
    at Module._compile (module.js:570:32)
    at loader (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/dev/Leaflet.Control.NestedLayers/
node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mnt/c/dev/Leaflet.Control.NestedLayers/test/Leaflet.LayerHierarchy.MapServer
Parser.spec.js:2:1)
    at Module._compile (module.js:570:32)
    at loader (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/dev/Leaflet.Control.NestedLayers/
node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/mocha/lib/mocha.js:495:10)
    at loadAndRun (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/mocha/bin/_mocha:426:22)
    at rerun (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/mocha/bin/_mocha:454:5)
    at /mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/mocha/bin/_mocha:462:7
    at StatWatcher.<anonymous> (/mnt/c/dev/Leaflet.Control.NestedLayers/node_modules/mocha/lib/utils.js:
196:9)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:191:7)
    at StatWatcher._handle.onchange (fs.js:1501:10)
```

##  CF.
#2364, #5489, #3958
https://github.com/Esri/esri-leaflet/issues/969
Others?

**Comment by colbin8r** [comment]
I suppose I should mention that I've considered some of these options, but haven't had any luck/lack knowledge on how to do them so far:

1. Polyfilling/stubbing the window global (I've explored this some using jsdom with no luck)
2. Ejecting/removing the leaflet dependency entirely (not likely since there are obvious dependencies)
3. Running leaflet-related unit tests with PhantomJS

**Comment by jieter** [comment]
[leaflet-headless](https://github.com/jieter/leaflet-headless) does use your first option using jsdom. Not yet updated for use with Leaflet 1.1.0, but 1.0.3 should work fine.

**Comment by colbin8r** [comment]
@jieter I really like your [leaflet-headless](https://github.com/jieter/leaflet-headless) package! I've been using it extensively up to this point. In fact, although I haven't extensively tested it, I'm using Leaflet 1.1.0 and it seems to work fine so far.

My problem actually stems from a package that depends on `leaflet` proper, though: [esri-leaflet](https://github.com/Esri/esri-leaflet). It depends directly on `leaflet`, and I'm not sure how to leverage leaflet-headless in this case. (See the issue I filed there: https://github.com/Esri/esri-leaflet/issues/969)

By the way, thanks for maintaining leaflet-headless! I looked at how you shimmed `window` and a few other things using jsdom and was both in awe and shaking my head simultaneously. 😆

**Comment by cherniavskii** [comment]
@colbin8r I also stuck with the same problem with Leaflet and Mocha tests a long time ago. I used [mocha-phantomjs](https://github.com/nathanboktae/mocha-phantomjs) runner and it worked perfectly ;)
