### ISSUE TITLE
Can't build docs with node 12.16.1 LTS

### ISSUE THREAD

**Issue by pkrasicki** [Leaflet/Leaflet#7021]
Building docs with current LTS version of Node.js fails with error:

```
npm run docs

> leaflet@1.6.0 docs /home/user/Leaflet
> node ./build/docs.js

Building Leaflet documentation with Leafdoc ...
fs.js:35
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (/home/user/Leaflet/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/user/Leaflet/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/user/Leaflet/node_modules/sander/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leaflet@1.6.0 docs: `node ./build/docs.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leaflet@1.6.0 docs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mourner** [comment]
Looks like an issue with Gulp v3: https://timonweb.com/posts/how-to-fix-referenceerror-primordials-is-not-defined-error/

**Comment by mondeja** [comment]
I can replicate this issue with node version `13.13.0`.
