### ISSUE TITLE
Broken tests in MapSpec.js

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7110]
I've found some tests that look passing, but in fact they do not serve their purpose.

https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/map/MapSpec.js#L49-L54

Correct property should be `_leaflet_id`

**Comment by johnd0e** [comment]
https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/map/MapSpec.js#L56-L71

This test will pass even without `map.disable()`, because map need to be initialized first (set view), and it's container must be attached to DOM.

**Comment by johnd0e** [comment]
https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/map/MapSpec.js#L553-L565
This test depends on map state that should be changed in some other test (setView).
If in some conditions map do not get ready that this test just never executed.

Two more tests with the same problem are here:
<details>

https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/map/MapSpec.js#L567-L580

https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/map/MapSpec.js#L582-L597
</details>

**Comment by johnd0e** [comment]
https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/map/MapSpec.js#L1031-L1038

`L.Browser.any3d = true;` has no effect here, as `L.Browser` object is 'frozen'.
In fact, this case does not require that.

And same is here:
<details>

https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites
/map/MapSpec.js#L1040-L1047
</details>

**Comment by johnd0e** [comment]
https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/map/MapSpec.js#L218-L235

On line 228 `map.options.crs` mock installed, but never restored.
This lead to later error here: https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/geo/CRSSpec.js#L24-L30

```
CRS.EPSG3857
project
projects geo coords into meter coords correctly‣
ExpectationError: Unexpected call: project(LatLng(50, 30))
    Expected project(LatLng(62.184756, 6.923933)[, ...]) once (never called)
    Expected project(LatLng(62.140484, 6.926335)[, ...]) once (never called)
    at Object.fail (file:///C:/D/repos/Leaflet/node_modules/sinon/pkg/sinon.js:1621:25)
    at Object.invokeMethod (file:///C:/D/repos/Leaflet/node_modules/sinon/pkg/sinon.js:1826:25)
    at Object.project (file:///C:/D/repos/Leaflet/node_modules/sinon/pkg/sinon.js:1702:35)
    at Context.<anonymous> (suites/geo/CRSSpec.js:26:15)
```

(It's observed in Chrome and Firefox but not in PhantomJS)
