### ISSUE TITLE
Removing a map on GridLayer's 'load' event causes exception

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7116]
https://jsbin.com/dewozac/edit?js,console,output
```
TypeError: Cannot read property '_leaflet_pos' of undefined
    at Li (https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5:20939)
    at i._getMapPanePos (https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5:42845)
    at i._getNewPixelOrigin (https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5:43202)
    at i._move (https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5:39745)
    at i._onZoomTransitionEnd (https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5:46671)
```
(This looks similar to #6115)

The same without zoom in - leads to different exception:
```
TypeError: Cannot read property '_fadeAnimated' of null
    at i._tileReady (https://unpkg.com/leaflet@1.6.0/dist/leaflet.js:5:111431)
```

Note: originally observed in test from `GridLayerSpec.js`:
<details>

https://github.com/Leaflet/Leaflet/blob/1ae785b73092fdb4b97e30f8789345e9f7c7c912/spec/suites/layer/tile/GridLayerSpec.js#L145-L164
</details>

**Comment by julienr** [comment]
I am also running into this while using leaflet in automated tests and monkeypatching the `_getMapPanePos` method with this seems to work while not breaking anything as far as I can tell. I haven't thoroughly tested everything though:
```
  _getMapPanePos: function () {
    if (this._mapPane) {
      return originalGetMapPanePos.call(this)
    } else {
      return new L.Point(0, 0)
    }
  }
```

I am not sure if this is the right fix, but may be handy as a temporary workaround.
