### ISSUE TITLE
Tests failing on IE

### ISSUE THREAD

**Issue by johnd0e** [Leaflet/Leaflet#7414]
Tests failing on IE11:
`npm run test-nolint -- --browsers IE`
20 tests failed.
<details>

```
IE 11.0 (Windows 10) ImageOverlay _image when loaded should raise the load event FAILED
        TypeError: Argument not optional
           at raiseImageEvent (spec/suites/layer/ImageOverlaySpec.js:66:4)
           at Anonymous function (spec/suites/layer/ImageOverlaySpec.js:74:5)
IE 11.0 (Windows 10) ImageOverlay _image when load fails should raise the error event FAILED
        TypeError: Argument not optional
           at raiseImageEvent (spec/suites/layer/ImageOverlaySpec.js:66:4)
           at Anonymous function (spec/suites/layer/ImageOverlaySpec.js:83:5)
IE 11.0 (Windows 10) ImageOverlay _image when load fails should change the image to errorOverlayUrl FAILED
        TypeError: Argument not optional
           at raiseImageEvent (spec/suites/layer/ImageOverlaySpec.js:66:4)
           at Anonymous function (spec/suites/layer/ImageOverlaySpec.js:88:5)
IE 11.0 (Windows 10) ImageOverlay #setZIndex should update the z-index of the image if it has allready been added to the map FAILED
        Error: expected 1 to equal '1'
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.equal (node_modules/expect.js/index.js:216:5)
           at Anonymous function (node_modules/expect.js/index.js:69:13)
           at Anonymous function (spec/suites/layer/ImageOverlaySpec.js:111:4)
IE 11.0 (Windows 10) ImageOverlay #setZIndex should set the z-index of the image when it is added to the map FAILED
        Error: expected 10 to equal '10'
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.equal (node_modules/expect.js/index.js:216:5)
           at Anonymous function (node_modules/expect.js/index.js:69:13)
           at Anonymous function (spec/suites/layer/ImageOverlaySpec.js:121:4)
IE 11.0 (Windows 10) ImageOverlay #setZIndex should use the z-index specified in options FAILED
        Error: expected 20 to equal '20'
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.equal (node_modules/expect.js/index.js:216:5)
           at Anonymous function (node_modules/expect.js/index.js:69:13)
           at Anonymous function (spec/suites/layer/ImageOverlaySpec.js:127:4)
IE 11.0 (Windows 10) Marker.Drag drag in CSS scaled container drags a marker with mouse, compensating for CSS scale FAILED
        expected 0 to be within -50..-30 (node_modules/expect.js/index.js:102)
WARN: 'Deprecated use of _flat, please use L.LineUtil.isFlat instead.'
WARN: 'Deprecated use of _flat, please use L.LineUtil.isFlat instead.'
IE 11.0 (Windows 10): Executed 602 of 688 (7 FAILED) (skipped 1) (0 secs / 11.673 secs)
05 02 2021 12:06:49.768:WARN [web-server]: 404: /000
IE 11.0 (Windows 10) Map #invalidateSize pans by the right amount when growing in 1px increments FAILED
        Error: expected 0 to equal 1
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.equal (node_modules/expect.js/index.js:216:5)
           at Anonymous function (node_modules/expect.js/index.js:69:13)
           at Anonymous function (spec/suites/map/MapSpec.js:649:4)
IE 11.0 (Windows 10) Map #invalidateSize pans by the right amount when shrinking in 1px increments FAILED
        Error: expected 0 to equal -1
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.equal (node_modules/expect.js/index.js:216:5)
           at Anonymous function (node_modules/expect.js/index.js:69:13)
           at Anonymous function (spec/suites/map/MapSpec.js:667:4)
IE 11.0 (Windows 10) Map #invalidateSize emits a move event if the size has changed FAILED
        Error: expected false to be truthy
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.ok (node_modules/expect.js/index.js:115:5)
           at Anonymous function (node_modules/expect.js/index.js:499:7)
           at Anonymous function (spec/suites/map/MapSpec.js:700:4)
IE 11.0 (Windows 10) Map #invalidateSize emits a moveend event if the size has changed FAILED
        Error: expected false to be truthy
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.ok (node_modules/expect.js/index.js:115:5)
           at Anonymous function (node_modules/expect.js/index.js:499:7)
           at Anonymous function (spec/suites/map/MapSpec.js:710:4)
IE 11.0 (Windows 10) Map #invalidateSize debounces the moveend event if the debounceMoveend option is given FAILED
        Error: expected false to be truthy
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.ok (node_modules/expect.js/index.js:115:5)
           at Anonymous function (node_modules/expect.js/index.js:499:7)
           at Anonymous function (spec/suites/map/MapSpec.js:724:4)
IE 11.0 (Windows 10) Map #invalidateSize correctly adjusts for new container size when view is set during map initialization (#6165) FAILED
        Error: expected 0 to equal 100
           at Assertion.prototype.assert (node_modules/expect.js/index.js:102:7)
           at Assertion.prototype.equal (node_modules/expect.js/index.js:216:5)
           at Anonymous function (spec/suites/map/MapSpec.js:745:4)
IE 11.0 (Windows 10) Map #fitBounds after layers set Snaps to a number after adding tile layer FAILED
        Error: Access is denied.

           at createTile (src/Leaflet.js:11713:5)
           at _addTile (src/Leaflet.js:11448:5)                                                                                        12:08
           at _update (src/Leaflet.js:11345:7)
           at _setView (src/Leaflet.js:11206:7)
           at _resetView (src/Leaflet.js:11161:5)
           at onAdd (src/Leaflet.js:10798:5)
           at _layerAdd (src/Leaflet.js:6566:5)
           at Events.fire (src/Leaflet.js:583:8)
           at _resetView (src/Leaflet.js:4167:6)
           at setView (src/Leaflet.js:3164:5)
IE 11.0 (Windows 10) Map.Drag mouse events in CSS scaled container change the center of the map, compensating for CSS scale FAILED
        expected 31.952162238024975 to be within 21.943..21.9431 (node_modules/expect.js/index.js:102)
IE 11.0 (Windows 10) Map.Drag touch events change the center of the map FAILED
        Object doesn't support this action (node_modules/prosthetic-hand/dist/prosthetic-hand.js:624)
IE 11.0 (Windows 10) Map.Drag touch events does not change the center of the map when finger is moved less than the drag threshold FAILED
        Object doesn't support this action (node_modules/prosthetic-hand/dist/prosthetic-hand.js:624)
IE 11.0 (Windows 10) Map.Drag touch events reset itself after touchend FAILED
        Object doesn't support this action (node_modules/prosthetic-hand/dist/prosthetic-hand.js:624)
IE 11.0 (Windows 10) Map.TouchZoom Increases zoom when pinching out FAILED
        Object doesn't support this action (node_modules/prosthetic-hand/dist/prosthetic-hand.js:624)
IE 11.0 (Windows 10) Map.TouchZoom Decreases zoom when pinching in FAILED
        Object doesn't support this action (node_modules/prosthetic-hand/dist/prosthetic-hand.js:624)
IE 11.0 (Windows 10): Executed 685 of 688 (20 FAILED) (skipped 3) (27.861 secs / 22.944 secs)
```
</details>

- [x] (3) `ImageOverlaySpec` is broken because image loading event simulation does not work (but it's possible to rewrite in other way).
      Easy to fix using `domEvent.initEvent(event, false, false);`
- [x] (3) Some are easy to fix:
      `ImageOverlay #setZIndex should update the z-index`
      `Error: expected 20 to equal '20'`.
- [ ] (2) `Marker/Map drag in CSS scaled container`
- [x] (6) `Map #invalidateSize`
      Easy to fix. Cause: in IE when `container.style.height` is not set, `container.clientWidth` is always 0, despite `container.style.width` value.
- [ ] (5) Some are broken because `prosthetic-hand` seems not support IE (https://github.com/Leaflet/prosthetic-hand/issues/22).
      `Object doesn't support this action (node_modules/prosthetic-hand/dist/prosthetic-hand.js:624)`
- [x] (1) `Map #fitBounds after layers set Snaps to a number after adding tile layer FAILED`
      Easy to fix, replacing "file:///dev/null" with "" (done in #7451).
      <details>

      ```
        Error: Access is denied.

           at createTile (src/Leaflet.js:11713:5)
           at _addTile (src/Leaflet.js:11448:5)
           at _update (src/Leaflet.js:11345:7)
           at _setView (src/Leaflet.js:11206:7)
           at _resetView (src/Leaflet.js:11161:5)
           at onAdd (src/Leaflet.js:10798:5)
           at _layerAdd (src/Leaflet.js:6566:5)
           at Events.fire (src/Leaflet.js:583:8)
           at _resetView (src/Leaflet.js:4167:6)
           at setView (src/Leaflet.js:3164:5)
      ```
      </details>

**Comment by johnd0e** [comment]
Additionally, tests failing on IE10:
- [ ] https://github.com/Leaflet/Leaflet/blob/436430db4203a350601e002c8de6a41fae15a4bf/spec/suites/map/handler/Map.KeyboardSpec.js#L2-L9
- [ ] (4) IE 10.0 (Windows 10) ImageOverlay _image2 uses crossOrigin option value true FAILED
      Error: expected null to equal ''/'anonymous'/'use-credentials'
- [ ] (4) IE 10.0 (Windows 10) TileLayer options uses crossOrigin value true FAILED
      Error: expected null to equal ''/'anonymous'/'use-credentials'

**Comment by johnd0e** [comment]
IE9 and IE8 failed to start.

In fact I have only IE11 installed, all others were emulated, as per docs: https://github.com/karma-runner/karma-ie-launcher#readme

**Comment by johnd0e** [comment]
So far only 2 tests are still broken (Marker/Map drag in CSS scaled container)

**Comment by jonkoops** [comment]
Closing this issue as we have decided to drop support for Internet Explorer in a future version of Leaflet (see #6136).
