### ISSUE TITLE
project

### ISSUE THREAD

**Issue by jonkoops** [Leaflet/Leaflet#8373]

**Comment by shivamchourasia4** [comment]
I would like to work on this too. Can you please assign this to me?

**Comment by Satyabrat-Ojha** [comment]
I would also like to contribute, can you please assign it to me?

**Comment by jonkoops** [comment]
I'm sorry, but someone already claimed this issue.

**Comment by alfawal** [comment]
I was trying to port some of the tests from ProjectionSpec, I am not sure if I did get the idea right.

The test case:
```js
it("projects the southwest corner of the world", () => {
	console.log(2, map.project(L.latLng(-85.0511287798, -180)))
	expect(map.project(L.latLng(-85.0511287798, -180))).near([5.6, 0]);
});
```

The output:
```sh
LOG: 2, Object{x: 5.551115123125783e-17, y: 0.9999999999997871}
Chrome Headless 106.0.5249.119 (Windows 10): Executed 1027 of 1089 (1 FAILED) (skipped 11) (0 secs / 8.856 secs)
LOG: 'expected: Point(5.6, 0)'
Chrome Headless 106.0.5249.119 (Windows 10): Executed 1027 of 1089 (1 FAILED) (skipped 11) (0 secs / 8.856 secs)
Chrome Headless 106.0.5249.119 (Windows 10) Map #project projects the southwest corner of the world FAILED
        Error: expected 5.551115123125783e-17 to be within 4.6..6.6
            at Assertion.assert (node_modules/expect.js/index.js:96:13)
            at Assertion.within (node_modules/expect.js/index.js:248:10)
            at Function.within (node_modules/expect.js/index.js:499:17)
            at expect.Assertion.near (spec/suites/SpecHelper.js:6:7)
            at Context.<anonymous> (spec/suites/map/MapSpec.js:2427:56)
```

**Comment by sumit851** [comment]
i am interested in this issue .can i contribute to this issue i have basic knowledge on html css jquery bootstrap java also.

**Comment by dhiraj0911** [comment]
@Satyabrat-Ojha if you are not working on it please assign to me

**Comment by AshwinNema** [comment]
Hi,
I am new to open source. Can I take up this issue?

**Comment by Falke-Design** [comment]
Hi @AshwinNema if you want, you can work on this. Please take a look into our comments of #8636

**Comment by sarmadH97** [comment]
Hi @AshwinNema , are you working on this?

I would like to contribute to it @Falke-Design

**Comment by Falke-Design** [comment]
@sarmadH97 when you look through the linked PRs, you will see that #9303 is already existing.
Please search for another one without a PR
