### ISSUE TITLE
remove() doesn't check that parent has that child causing an exception

### ISSUE THREAD

**Issue by MaximRikel** [Leaflet/Leaflet#8432]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

Remove function causes an exception when using Leaflet.markercluster.

`function remove(el) {
  	var parent = el.parentNode;
  	if (parent) {
  		parent.removeChild(el);
  	}
  }`

When zooming in on a cluster that contains multiple markers at the same location I sometimes get an exception:

`Uncaught DOMException DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at _remove (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:2136:1)
    at _removeIcon (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:7240:1)
    at onRemove (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:7088:1)
    at removeLayer (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:6319:1)
    at removeLayer (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:6459:1)
    at removeLayer (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:6593:1)
    at <anonymous> (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1801:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1828:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursively (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1841:1)
    at _recursivelyRemoveChildrenFromMap (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1782:1)
    at _animationZoomIn (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1257:1)
    at _mergeSplitClusters (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:1138:1)
    at _zoomEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js:978:1)
    at fire (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:624:1)
    at _moveEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:3996:1)
    at _onZoomTransitionEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:4463:1)
    at _catchTransitionEnd (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:4381:1)
    at handler (/Users/maximfalkor/Projects/Falkor/atreyu/node_modules/leaflet/dist/leaflet-src.js:2555:1)`

### Expected behavior

The function should check that the parent contains this child before attempting to remove

### Current behavior

Exception

### Environment

- Leaflet version: 1.8.0
- Browser (with version): Chrome
- OS/Platform (with version): Mac 12.5.1

**Comment by mourner** [comment]
I'm not sure it should — it's helpful to see this error because it usually indicates a deeper issue we should find the root cause of. Can you create a minimal test case of a situation where this happens? (I see it's something related to the markercluster plugin?)

**Comment by MaximRikel** [comment]
I wasn't able to recreate this bug with markercluster base code and I'm not at liberty to share my clients code. I hope you are able to solve this without an example but if not I'll try to find the time to write something reproducible.
