### ISSUE TITLE
unbindTooltip does not remove focus listeners

### ISSUE THREAD

**Issue by bielfrontera** [Leaflet/Leaflet#9071]
### Checklist

- [X] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [X] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [X] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [X] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

1. Open this [jsfiddle link](https://jsfiddle.net/bielfrontera/50Lcfs96/8/)
2. Wait two seconds until the tooltip is unbinded
3. Click on the the marker. You'll see this error message at the browser console:
``` 
Tooltip.js:399 Uncaught TypeError: Cannot set properties of null (setting '_source')
    at e.<anonymous> (Tooltip.js:399:19)
    at SVGPathElement.o (DomEvent.js:108:13)
```

### Expected behavior

After the tooltip is unbinded, focus listeners should be removed (or at least, that listener should ensure that `this._tooltip` is not `null`)

### Current behavior

An error is raised if you click on a layer with an unbinded tooltip. 

### Minimal example reproducing the issue

https://jsfiddle.net/bielfrontera/50Lcfs96/8/

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Google Chrome v 115.0.5790.170
- OS/Platform (with version): Ubuntu 20.04

**Comment by Falke-Design** [comment]
I can confirm the error but only in Chrome.

**Comment by mohasabbasi** [comment]
5845ba0

**Comment by hollowM1ke** [comment]
Hello. I've created a [pull request](https://github.com/Leaflet/Leaflet/pull/9232). I would love to have your feedback.
@bielfrontera 

- Leaflet version: 1.9.2
- Browser version: 120.0.6099.225 (Official Build) (64-bit)
- OS: Windows 10

**Comment by notbadjon** [comment]
I'm stuck on this issue. Is there a known workaround? Or should I just avoid tooltips for my use-case?
