### ISSUE TITLE
Uncaught Error: Map container not found.

### ISSUE THREAD

**Issue by SignG3T** [Leaflet/Leaflet#9562]
### Checklist

- [x] I've looked at the [documentation](https://leafletjs.com/reference.html) to make sure the behavior isn't documented and expected.
- [x] I'm sure this is an issue with Leaflet, not with my app or other dependencies (Angular, Cordova, React, etc.).
- [x] I've searched through the [current issues](https://github.com/Leaflet/Leaflet/issues) to make sure this hasn't been reported yet.
- [x] I agree to follow the [Code of Conduct](https://github.com/Leaflet/Leaflet/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.

### Steps to reproduce

When I load the page

### Expected behavior

I expected the map to be visible

### Current behavior

When I load the site it gives me a strange error:
Uncaught Error: Map container not found.
    at e._initContainer (Map.js:1092:10)
    at e.initialize (Map.js:136:8)
    at new e (Class.js:24:20)
    at Object.map (Map.js:1750:9)
    at index.html:165:37

### Environment

- Leaflet version: 1.9.4
- Browser (with version): Chrome 131.0.6778.204
- OS/Platform (with version): Windows 11

**Comment by SignG3T** [comment]
resolved.
